apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: speaker
spec:
  selector:
    matchLabels:
      app: speaker
  replicas: 1 # deployment runs 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: speaker
    spec:
      containers:
      - name: speaker
        image: iad.ocir.io/rodrigocandidosilva/speaker
        imagePullPolicy: Always
        ports:
        - name: speaker
          containerPort: 8080 #Endpoint is at port 8080 in the container
          protocol: TCP
      imagePullSecrets:
      - name: wercker
---
apiVersion: v1
kind: Service
metadata:
  name: speaker
  labels:
    app: speaker
spec:
  type: LoadBalancer #Exposes the service port
  ports:
  - port: 30000
    protocol: TCP
    targetPort: 8080
  selector:
    app: speaker
---