apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: speaker-app
spec:
  selector:
    matchLabels:
      app: speaker-app
  replicas: 1 # deployment runs 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: speaker-app
    spec:
      containers:
      - name: speaker-app
        image: iad.ocir.io/rodrigocandidosilva/microprofile-speaker:${WERCKER_GIT_BRANCH}-${WERCKER_GIT_COMMIT}
        imagePullPolicy: Always
        ports:
        - name: speaker-app
          containerPort: 8080 #Endpoint is at port 8080 in the container
          protocol: TCP
      imagePullSecrets:
      - name: wercker
---
apiVersion: v1
kind: Service
metadata:
  name: speaker-svc
  labels:
    app: speaker-app
spec:
  type: NodePort #Exposes the service as a node port
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: speaker-app
---